### ISSUE TITLE
Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/coding-standards#278]
Fatal error is being thrown by `phpcs`. Reported in https://github.com/squizlabs/PHP_CodeSniffer/issues/3196, determined to be a WPCS error and fixed here https://github.com/WordPress/WordPress-Coding-Standards/commit/7cd46bed1e6a7a2af3fe24c7f4a044da3076d8f4

**Suggested resolution:** bump WPCS to latest (2.3.0)

**Workaround:**
You can temporarily work around the error by manually requiring the latest version of `wpcs` but calling it the latest supported version by HM coding standards, e.g.:
```json
"require-dev": {
    "humanmade/coding-standards": "^1.1",
    "wp-coding-standards/wpcs": "2.3.0 as 2.2.1"
}
```

**Comment by tfrommen** [comment]
Fixed in #282.

**Comment by CherryGot** [comment]
I still face this issue with php@8.1.13, wpcs@2.3.0 and phpcs@3.7.1. Has the fix not made it to the release yet?

**Comment by tfrommen** [comment]
@CherryGot the `1.2.0` release of the HM Coding Standards pull in the `2.3.0` version of the WP Coding Standards. Those have some PHP 8 type issues fixed, but sadly not all of them (see https://github.com/WordPress/WordPress-Coding-Standards/pull/1935). Can you check what issue you are seeing exactly?

**Comment by CherryGot** [comment]
@tfrommen Yes, you're right. The latest version of WPCS with fixes for PHP8+ hasn't released yet. I found a release tag for this particular fix here which I was able to use https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/2.3.0-fix-vsprintf but it's on the dev branch. Well, something's better than nothing, haha. Thanks for that link to the milestone, will keep an eye on it.
